name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pandas==1.1.4
  - pytorch=1.7.0
  - pytorch-lightning=1.0.8
  - dask=2.30.0
  - pyarrow=0.15.1
  - pip=20.2.4
  - cudatoolkit=11.0  
  - pip:
      - fire==0.3.1
      - tensorboard==2.4.0  
